### ISSUE TITLE
Default title postfix no longer works?

### ISSUE THREAD

**Issue by khalwat** [bjornbjorn/SEO-Lite#17]
First, thank you for SEO Lite, it's a great tool!

I upgraded a site to the latest version of SEO Lite, and found that it isn't appending the "Default title postfix" anymore, as of version 1.4.9.3 running on EE 2.7.3

I have the field set to:

 |&nbsp;

...to put a pipe and a space between the title and the default title... but it's no longer appearing in the `<title>` tags, so the words are mashed together.

Nothing else changed on the site other than updating to the latest SEO Lite.  Any ideas?

**Comment by bjornbjorn** [comment]
Hi khalwat,

default title postfix is only applied if an entry is found. Is it working on entry pages or not working at all? When testing it now it seems to work fine for me with 1.4.9.3

**Comment by khalwat** [comment]
So it turns out to be really stupid.  It appears that the update to the latest SEO Lite wiped out the "Template" code, where I'd put the | divider in for non-entry pages.  I replaced that, and it seems to work as expected now.

**Comment by bjornbjorn** [comment]
Hm, glad to hear it's working. An update shouldn't wipe your preferences though, are you sure you didn't uinstall/install it?

**Comment by khalwat** [comment]
I just updated it with DevDemon.com Updater... which I don't think uninstalls and re-installs, because that would cause data loss on a rather large scale...
