### ISSUE TITLE
Extra Image when using Assets + Amazon S3

### ISSUE THREAD

**Issue by madebyspark** [bjornbjorn/SEO-Lite#19]
Hey there!

First, thanks for such a great plugin - so helpful and easy to use!

I am using the extra:image config and my field is an assets field, with images from S3. The returned image url is coming back:

```
 {filedir_}image-name.jpg
```

Is this a bug or something else causing this?

Thanks so much!
Danielle

**Comment by bjornbjorn** [comment]
Hi,

that's strange - normally the {filedir_} part of that returned string should contain a reference to the filedir id, such as {filedir_1} and that would be replaced by SEO Lite creating a valid URL to the image.

I haven't tested Assets with S3 so I don't know if that is how Assets stores metadata when using S3, but I doubt it.

If you look in your exp_channel_data table and the data stored in the field_id_45 column (where you replace 45 with the actual field id you're using for the image in this case) - are all values stored as {filedir_} or just this one?

**Comment by jeffBenusa** [comment]
Afternoon Bjørn - I'm curious if you ever found a solution for images over amazon S3?  I have the same error as mentioned above.  I'm using the P&T plugin Assets and my images are not being stored with {filedir_}.  Any ideas?
