### ISSUE TITLE
Error: The configuration file seolite.php does not exist.

### ISSUE THREAD

**Issue by ThorntonStuart** [bjornbjorn/SEO-Lite#22]
Hi,

When saving from the SEO Lite tab file on a channel I am getting this error. I tried to use the patch that you were able to acquire here:

https://ellislab.com/forums/viewthread/248551/#1071165

But this triggered another issue, in that when attempting to save I get a 'Cannot Update Entry' error which points out that the 'Author' is a required field, despite having 'admin' selected.

**Comment by bjornbjorn** [comment]
Hi, don't apply this patch for 3.1 - it was only needed for 3.0.1
