### ISSUE TITLE
No longer works on EE2?

### ISSUE THREAD

**Issue by MobsterGit** [bjornbjorn/SEO-Lite#23]
I just updated SEO Lite and added it to my third_parties folder and no go.  Does this no longer work for versions less than 3.0?

**Comment by MobsterGit** [comment]
Oops, I just found documentation for the last release for EE2 Latest release for EE2 is 1.4.9.3
In particular, I'm looking for dynamic facebook og: tags.  Is anything included in version 1.4.9.3?

**Comment by bjornbjorn** [comment]
Yes, "extra tags" are supported in 1.4.9.3 as well.

This works exactly the same as for the EE3 version so you can read about it in the docs here:

http://wedoaddons.com/seo-lite/extra-tags

**Comment by MobsterGit** [comment]
Sorry, I know you closed this but what config file do I drop the arrays into in EE2?  system/config or config/seolite.php?  I see this question has been asked before.  

I appreciate your help.

**Comment by bjornbjorn** [comment]
No problem, it should go in your main config.php (ExpressionEngine's config file).

system/expressionengine/config/config.php

**Comment by MobsterGit** [comment]
Worked like a charm.  On a side not for other noob's (like myself) in EE2 you need to change $env_config to $config

Thanks a million!

**Comment by bjornbjorn** [comment]
Yes, $env_config is for those who use FocusLab LLC's master config .. I guess you got that from somewhere else (the gist?)? If not let me know cause there shouldn't be any mention of $env_config in the docs.

**Comment by MobsterGit** [comment]
I got it from https://gist.github.com/bjornbjorn/4039233

**Comment by MobsterGit** [comment]
To follow the trail that led me to there.  http://expressionengine.stackexchange.com/questions/16890/populate-meta-tag-dynamically  

I'm just posting for other folks looking.

**Comment by bjornbjorn** [comment]
Excellent, thanks for the clarification!
