### ISSUE TITLE
Where are these characters coming from?

### ISSUE THREAD

**Issue by smockensturm** [bjornbjorn/SEO-Lite#24]
​​​​​​​​"&#8203;​​​​​​​​&#8203;"

These are getting injected with (and just before) your plug-ins <title>...</title> output.

**Comment by bjornbjorn** [comment]
Never seen that before - what EE version?

**Comment by smockensturm** [comment]
2.10.1

to be clear, source reads:

`"&#8203;&#8203;"`

**Comment by bjornbjorn** [comment]
Are you sure that this does not exist in your template _or_ your SEO Lite template?

Try removing the SEO Lite tag, is it still there? If so, try to clear out the SEO Lite template (just copy the contents to a text editor and then save it as empty) - is it still output then?

**Comment by smockensturm** [comment]
Yeah. OK. Must have pasted some trash in there.

I went back to the SEO Lite template, cleared it out and typed it all back in (no pasting!) and all is well. Thanks for the help.

**Comment by bjornbjorn** [comment]
Yeah, some code editors will do that. Good stuff, I'll close this one then.
