### ISSUE TITLE
EE3 - deleting a post errors...

### ISSUE THREAD

**Issue by paulcripps** [bjornbjorn/SEO-Lite#26]
We're running EE3.1.2 and SEO Lite 1.5.1

When logged into the CMS, on entries view we deleted an entry, confirmed in the popup, then got the following erros:

    Notice Undefined index: entry_ids user/addons/seo_lite/tab.seo_lite.php, line 247 show details
    Severity: E_NOTICE Warning

    Invalid argument supplied for foreach()
    user/addons/seo_lite/tab.seo_lite.php, line 247 show details

    Severity: E_WARNING Warning
    Cannot modify header information - headers already sent by (output started at         
    /home/XXX/public_html/admin/ee/legacy/core/Exceptions.php:112)

    ee/legacy/core/Input.php, line 249 show details
    Severity: E_WARNING Warning

    Cannot modify header information - headers already sent by (output started at 
    /home/XXX/public_html/admin/ee/legacy/core/Exceptions.php:112)

    ee/legacy/libraries/Functions.php, line 437 show details
    Severity: E_WARNING

Ellis labs are looking at a few other issues and fixed this one our server, its around line 245 as its looking for an associative array with an element named ‘entry_ids’ and EE was just feeding it an array of entry ids.

**Comment by bjornbjorn** [comment]
Thanks for the heads up, this wasn't an issue in 3.1.1 so it must be something new to 3.1.2. Will look into it.

**Comment by bjornbjorn** [comment]
Actually, seems this was something that changed in EE3 so it was an issue in 3.1.1. I fixed it here 7451fc2b2617665d15dc5c918a84ee26eb3c0408 and pushed a new release. Thanks again for the report!
