### ISSUE TITLE
Publisher support

### ISSUE THREAD

**Issue by reinos** [bjornbjorn/SEO-Lite#29]
I have installed Seo Lite with the latest Publisher.  Unfortunately the urls and titles are not translated despite the addon support publiser.

Do i miss something?

**Comment by bjornbjorn** [comment]
Hi Reinos,

Publisher support is provided by a separate extension: https://github.com/bjornbjorn/seo_lite_publisher.ee_addon

I'll close this ticket. If you experience issue with Publisher support please open a new ticket in the [seo_lite_publisher repo](https://github.com/bjornbjorn/seo_lite_publisher.ee_addon). Thank!

**Comment by reinos** [comment]
Thanks!
