### ISSUE TITLE
Fatal error: Call to undefined method Cp::set_variable() in 

### ISSUE THREAD

**Issue by shubzda** [bjornbjorn/SEO-Lite#30]
Here is the error I am getting 
Fatal error: Call to undefined method Cp::set_variable() in /xxxx/system/expressionengine/third_party/seo_lite/mcp.seo_lite.php on line 97

running EE 2.11 

seo lite 1.3.5 

Jeff

Here is the code from that page where the line error is occurring. The plugin is working I just can't access the default page in EE admin. 

$vars['_form_base'] = $this->form_base;
$this->EE->cp->set_variable('cp_page_title', lang($lang_key));
$this->EE->cp->set_breadcrumb($this->base, lang('seo_lite_module_name'));

**Comment by bjornbjorn** [comment]
Upgrade to the latest version of SEO Lite, that will fix this.
